### ISSUE TITLE
Build fails with test failure

### ISSUE THREAD

**Issue by alexanderkoller** [coli-saar/am-tools#5]
I currently cannot build am-tools (MacOS, JDK 12) because the class `MRPEquality` cannot be found when the tests are compiled.

This is a bit urgent because I'd like to help Rezka debug the A* parser and can't do it without building am-tools.

Could someone look into this? It may be the same problem as #4, but it's hard to tell because the error message in #4 is a bit unspecific. @namednil, I believe you were going to look at #4?

```
dhcp104-196:am-tools koller$ ./gradlew clean build

> Task :createVersionFile
createVersionFile called. Path /Users/koller/Documents/workspace/am-tools/src/main/java/de/saar/coli/amrtagging

> Task :compileJava
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

> Task :compileTestGroovy
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.codehaus.groovy.reflection.CachedClass (file:/Users/koller/.gradle/caches/modules-2/files-2.1/org.codehaus.groovy/groovy-all/2.4.13/7e410735a50e495323dd4855ddd13ea7dad23ac1/groovy-all-2.4.13.jar) to method java.lang.Object.finalize()
WARNING: Please consider reporting this to the maintainers of org.codehaus.groovy.reflection.CachedClass
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

> Task :test FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':test'.
> failed to read class file /Users/koller/Documents/workspace/am-tools/build/classes/java/test/de/saar/coli/amrtagging/mrp/sdp/MRPEquality.class

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 45s
14 actionable tasks: 14 executed
```

**Comment by alexanderkoller** [comment]
I can still compile am-tools by skipping the tests with `./gradlew build -x test`, but this should still be fixed asap.

**Comment by namednil** [comment]
Yes, #4 is something that I wanted to look into but it's a bit tricky to fix a bug that I cannot reproduce, neither on my computer nor on the servers (both Linux, JDK 8). I'm not sure if it's a MacOS thing or a JDK 12 thing.
I'll set up a virtual machine with Ubuntu and JDK 12 and see if I can reproduce the issue.

**Comment by alexanderkoller** [comment]
I just checked, and it is a JDK 12 issue. With Java 8 on Mac, the tests go through without problems.

**Comment by alexanderkoller** [comment]
But with Java 8, I don't get the error message about illegal reflective access in Groovy, either. Java changed something about reflection somewhere between Java 8 and 10. Maybe we need to use a more recent version of Groovy to work around that?

**Comment by namednil** [comment]
Yes, I just came to a similar conclusion (https://github.com/gradle/gradle/issues/3118, https://github.com/gradle/gradle/issues/2995). Do you know how to update Groovy/Gradle?

**Comment by namednil** [comment]
When I upgrade groovy

```
testCompile 'org.codehaus.groovy:groovy-all:2.5.8'
```
and update gradle
```
./gradlew wrapper --gradle-version=6.0.1 --distribution-type=bin
```
it compiles but with a new warning:

```
$ ./gradlew test
Starting a Gradle Daemon (subsequent builds will be faster)

> Task :createVersionFile
createVersionFile called. Path /home/osboxes/am-tools/src/main/java/de/saar/coli/amrtagging

> Task :compileJava
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

> Task :test
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.codehaus.groovy.vmplugin.v7.Java7$1 (file:/home/osboxes/.gradle/caches/modules-2/files-2.1/org.codehaus.groovy/groovy/2.5.8/2f1e8ea55e625fe51e85ef35eb067f1d9c61772d/groovy-2.5.8.jar) to constructor java.lang.invoke.MethodHandles$Lookup(java.lang.Class,int)
WARNING: Please consider reporting this to the maintainers of org.codehaus.groovy.vmplugin.v7.Java7$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.0.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD SUCCESSFUL in 1m 11s
5 actionable tasks: 5 executed

```

**Comment by alexanderkoller** [comment]
I think that's another problem with Groovy and post-JDK-11 reflection: https://backstage.forgerock.com/knowledge/kb/article/a15048811

With `testCompile 'org.codehaus.groovy:groovy-all:3.0.0-rc-2'` and Gradle 6.0.1, everything seems to work fine.

Groovy 3 requires JDK 9 to compile. Is everyone up for upgrading to JDK 9?

**Comment by namednil** [comment]
I'm fine with using a more recent Java version if we also have it on the servers (perhaps in `/proj/irtg.shadow/`?) so we all can compile on the servers in the same environment and don't have to transfer jar files.

**Comment by alexanderkoller** [comment]
Ah, good point. Ok, I have installed JDK 13 and Gradle 6.0.1 into /proj/contrib, currently testing if that works.

**Comment by alexanderkoller** [comment]
JDK 13 is incompatible with the Gradle Shadow plugin which we use. But you can now compile am-tools on falken-1 as follows using JDK 12:

```
export JAVA_HOME=/proj/contrib/jdk-12.0.2
/proj/contrib/gradle-6.0.1/bin/gradle build
```

Could I ask you to make the change to the Gradle dependency and update the Gradle wrapper in am-tools to 6.0.1? Then we should let @jgroschwitz and @rezkaaufar and probably @weissenh know that that they should use JDK 12 on the servers and close this issue.
